// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myqedxuzjdlngbcgyyhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cWVkeHV6amRsbmdiY2d5eWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDg4OTYsImV4cCI6MjA3MjYyNDg5Nn0.s2pqrW_FtxNmR4gVmYAfK5XR19--L7L0uvxxIUQOOas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});